title: Site

tabs:

# content tab
  content:
    label: Pages
    icon: text
    sections:
      pages:
        type: pages

# config tab
  config:
    label: Config
    icon: cog
    fields:
      categories:
        label: Catégories
        type: tags
      intro-text:
        Label: Intro
        type: text
